### ISSUE TITLE
Nextjs `useLayoutEffect` warning.

### ISSUE THREAD

**Issue by piotrgrundas** [dromru/react-photoswipe-gallery#1163] opened 2023-05-26 08:09 UTC
**Describe the bug**
When using the lib with nextjs, it produces some nasty errors in the console.

```
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.

at Item (file:///Users/pete/Development/xxx/storefront/node_modules/.pnpm/react-photoswipe-gallery@2.2.7_photoswipe@5.3.7_prop-types@15.8.1_react@18.2.0/node_modules/react-photoswipe-gallery/dist/item.js:19:7)
```

```
react 18.2.0
react-intl 6.4.2
react-photoswipe-gallery 2.2.7
next 13.4.3
```

**Comment by IM-Deane** [comment] 2023-06-04 02:45
Any updates on this? I was planning to add this to a Nextjs project and don't want to run into any "gotchas".

**Comment by mortyccp** [comment] 2023-06-28 06:23
I think can make use of useIsomorphicLayoutEffect like https://github.com/streamich/react-use/blob/master/docs/useIsomorphicLayoutEffect.md

**Comment by renebakx** [comment] 2023-06-29 09:24
> I think can make use of useIsomorphicLayoutEffect like https://github.com/streamich/react-use/blob/master/docs/useIsomorphicLayoutEffect.md

I've tried that as well, but the component was to deeply nested in our code base and I couldn't find a proper place for that wrapper. Dynamic was simply a quicker solution :)

**Comment by akhmadullin** [comment] 2023-06-30 03:14
@piotrgrundas, you can add `'use client'` directive to the component, that uses `react-photoswipe-gallery`

```tsx
'use client'

import React, { FC } from 'react';
import { Gallery, Item } from 'react-photoswipe-gallery'
import 'photoswipe/dist/photoswipe.css'

const MyGallery: FC = () => {
    return (
        <Gallery>
            <Item>...</Item>
            <Item>...</Item>
            <Item>...</Item>
        </Gallery>
    )
}

export default MyGallery;
```

`'use client'` makes your component `Client component` and errors/warnings from console will disappear

___

Next Docs - https://nextjs.org/docs/getting-started/react-essentials#third-party-packages

**Comment by just-learning-1** [comment] 2023-07-06 03:07
> It's not a proper solution but I fixed the issue by loading the component that contains the gallery dynamic and disabling the server side rendering.
> 
> ```js
> import dynamic from 'next/dynamic'
> const ImageGallery = dynamic(() => import('@/components/image-gallery'), { ssr: false });
> ```

This works, but note the wrapper is important.

Discussions:
https://stackoverflow.com/a/68323914
https://github.com/vercel/next.js/discussions/13139

**Comment by mikkpokk** [comment] 2023-07-18 11:28
It can be fixed easily.

Must change following file: https://github.com/dromru/react-photoswipe-gallery/blob/master/src/item.ts
Remove L97:
```Javascript
const ref: ItemRef = useRef() as ItemRef
```

Remove L104 - L107:
```Javascript
useLayoutEffect(() => {
    set(ref, restProps)
    return () => remove(ref)
  }, Object.values(restProps))
```

Add new lines afterwards:
```Javascript
const tempRef = useRef()
ref = useCallback(node => {
   if (node) {
       tempRef.current = node
       set(tempRef, restProps)
   
       return () => remove(tempRef)
   }
}, Object.values(restProps))
```

This will fix the performance issues and warnings in SSR frameworks (Remix, Next.js)

**Comment by DanielRiveraHQ** [comment] 2023-08-30 18:58
@irudoy do you think this is good to merge? It will be great help

**Comment by mikkpokk** [comment] 2023-09-18 16:15
@DanielRiveraHQ Sorry, seems like package mantainers are not much active here.

Who ever lands here with the same issue and PR #1212 isn't still merged, you can use following install command instead:

``
npm i github:mikkpokk/react-photoswipe-gallery#main --save
``

Branch above applied #1212 PR fix into photoswipe release `2.2.7`

**Comment by kerns** [comment] 2023-10-06 22:49
> @DanielRiveraHQ Sorry, seems like package mantainers are not much active here.

If you want help maintaining a fork of this for next.js / or react more broadly, please reach out.

**Comment by AlexanderTserkovniy** [comment] 2023-10-08 23:27
reach out, or do anything, but please guys update the project, it is soooo simple, just merge the request and that's it. Please! So annoying seeing this huge issue.

**Comment by mikkpokk** [comment] 2023-10-27 23:06
@kerns I can help maintaining the new fork if you would like an extra pair of hands 🙂 I try to be as active as I can.

**Comment by MaximKondratev** [comment] 2023-10-30 08:11
I think we are going to return to this issue within two weeks, maybe month

**Comment by acelaya** [comment] 2023-10-30 08:13
Just FYI. This happens with other frameworks doing SSR, not only Next.js

**Comment by MaximKondratev** [comment] 2023-11-23 08:14
I released alpha version without useEffect or useLayoutEffect as alpha release to test. I would like to test in for some time in production before releasing as stable.

Please consider trying new version too to ensure it works properly.

```
yarn add react-photoswipe-gallery@v3.0.0-alpha.0
```

**Comment by acelaya** [comment] 2023-11-23 08:41
> I released alpha version without useEffect or useLayoutEffect as alpha release to test. I would like to test in for some time in production before releasing as stable.
> 
> Please consider trying new version too to ensure it works properly.

Just tested it and seems to be working pretty well. The update is straight forward.

**Comment by mikkpokk** [comment] 2023-11-23 18:29
@MaximKondratev I don't get it.. You hold back simple PR for months, which fixes mentioned issue directly just because you wanted to make your own major breaking changes on typescript and change compoent usage requirements?

#1305 VS #1212 - nothing straight forward in #1305.

Basically, all who want to maintain their project without applying breaking changes should accept buggy (version 2 haven't got that fix ever!) release because that nonsense?

**Comment by MaximKondratev** [comment] 2023-11-24 02:59
@mikkpokk  The main reason why i hold "simple" PR is because it did not fix the issue. I moved to useLayoutEffect for reason (bug in production which useLayoutEffect fixed), while your suggestion was to go back to useEffect.

I agree that usually it is better to hotfix instead of major, but sometimes you just can't do anything about decisions made earlier. Also useLayoutEffect warning is not a bug we can't leave with.

In that case breaking changes are okey as they are really not that big.

Thanks for your opinion.

PS

I think real hotfix would be to change useLayoutEffect to classic useIsomorphicLayoutEffect.

**Comment by mikkpokk** [comment] 2023-11-25 01:44
@MaximKondratev Please look carefully #1212. I did not suggest going back to `useEffect` ever. In fact, I suggested and made PR using `useCallback` hook from the beginning to destroy `useLayoutEffect`. Neither #1212 changed usage signature.

Suggesting `useIsomorphicLayoutEffect` is nonsense suggestion, since it would have introduced extra package. `useIsomorphicLayoutEffect` runs `useEffect` in SSR and `useLayoutEffect` on client-side. Which is, by the way, total nonsense hook, since SSR never-ever run useEffect. Hence, it makes random overhead on build code and would not solve peformance issues, what `useLayoutEffect` causes.

However, #1305 changes usage signature and the main goal wasn't to solve V2 `useLayoutEffect` issue. The main goal was to fix typings and refactoring usage signature. As a side-effect, it fixed the `useLayoutEffect`. 

That is the reason, why I ask, why you decided to hold back straight-forward fix to stable version for a months. Instead, you introduced new version with new usage signature and left V2 unstable.

**Comment by MaximKondratev** [comment] 2023-12-05 10:32
Closing this issue as v3.0.0 released and this should fix the problem. If you are struggling but can not upgrade, please feel free to downgrade to 2.2.6.

P.S.
Sorry @mikkpokk, I wanted to respond with more arguments but at the and I could not find strengths to keep this conversation. I don't think those arguments would matter anyway.

**Closed by MaximKondratev** 2023-12-05 10:32 UTC
