### ISSUE TITLE
Not working with Photoswipe v5+

### ISSUE THREAD

**Issue by natac13** [dromru/react-photoswipe-gallery#760] opened 2022-03-30 13:03 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by irudoy** [comment] 2022-04-01 20:25
Duplicate of https://github.com/dromru/react-photoswipe-gallery/issues/591

**Closed by irudoy** 2022-04-01 20:25 UTC
